#include "python_interface/include/python_interface.h"


BOOST_PYTHON_MODULE(data_struct){
    enum_<ExchangeType>("ExchangeType")
        .value("ExchangeType_MIN",ExchangeType_MIN)
        .value("ExchangeType_OKX",ExchangeType_OKX)
        .value("ExchangeType_BINANCE",ExchangeType_BINANCE)
        .value("ExchangeType_FTX",ExchangeType_FTX)
        .value("ExchangeType_XT",ExchangeType_XT)
        .value("ExchangeType_BYBIT",ExchangeType_BYBIT)
        .value("ExchangeType_COINBASE",ExchangeType_COINBASE)
        .value("ExchangeType_HUOBI",ExchangeType_HUOBI)
        .value("ExchangeType_GATEIO",ExchangeType_GATEIO)
        .value("ExchangeType_ZB",ExchangeType_ZB)
        .value("ExchangeType_MEXC",ExchangeType_MEXC)
        .value("ExchangeType_DERIBIT",ExchangeType_DERIBIT)
        .value("ExchangeType_KUCOIN",ExchangeType_KUCOIN)
        .value("ExchangeType_MAX",ExchangeType_MAX)
        .export_values()
    ;

    enum_<InstType>("InstType")
        .value("InstType_MIN",InstType_MIN)
        .value("SPOT",SPOT)
        .value("MARGIN",MARGIN)
        .value("SWAP",SWAP)
        .value("FUTURES",FUTURES)
        .value("OPTION",OPTION)
        .value("InstType_SPOT",InstType_SPOT)
        .value("InstType_MARGIN",InstType_MARGIN)
        .value("InstType_USDT_SWAP",InstType_USDT_SWAP)
        .value("InstType_BTC_SWAP",InstType_BTC_SWAP)
        .value("InstType_BUSD_SWAP",InstType_BUSD_SWAP)
        .value("InstType_C_SWAP",InstType_C_SWAP)
        .value("InstType_USDT_FUTURES",InstType_USDT_FUTURES)
        .value("InstType_BTC_FUTURES",InstType_BTC_FUTURES)
        .value("InstType_C_FUTURES",InstType_C_FUTURES)
        .value("InstType_OPTION",InstType_OPTION)
        .value("InstType_MAX",InstType_MAX)
        .export_values()
        ;

    enum_<pubsub::CommandType>("CommandType")
        .value("CMD_TYPE_MIN",pubsub::CMD_TYPE_MIN)
        .value("CMD_RPT_BALANCE",pubsub::CMD_RPT_BALANCE)
        .value("CMD_NEW_ORDER",pubsub::CMD_NEW_ORDER)
        .value("CMD_RPT_NEW_ORDER",pubsub::CMD_RPT_NEW_ORDER)
        .value("CMD_CANCEL_ORDER",pubsub::CMD_CANCEL_ORDER)
        .value("CMD_RPT_CANCEL_ORDER",pubsub::CMD_RPT_CANCEL_ORDER)
        .value("CMD_QUERY_ORDER",pubsub::CMD_QUERY_ORDER)
        .value("CMD_RPT_QUERY_ORDER",pubsub::CMD_RPT_QUERY_ORDER)
        .value("CMD_RPT_ORDER_RESPONSE",pubsub::CMD_RPT_ORDER_RESPONSE)
        .value("CMD_RPT_TRADE",pubsub::CMD_RPT_TRADE)
        .value("CMD_RPT_POSITION",pubsub::CMD_RPT_POSITION)
        .value("CMD_RPT_ORDER_TRADE",pubsub::CMD_RPT_ORDER_TRADE)
        .value("CMD_QUERY_ACCOUNT",pubsub::CMD_QUERY_ACCOUNT)
        .value("CMD_QUERY_POSITION",pubsub::CMD_QUERY_POSITION)
        .value("CMD_QUERY_BALANCE",pubsub::CMD_QUERY_BALANCE)
        .value("CMD_RPT_TOTAL_ACCOUNT",pubsub::CMD_RPT_TOTAL_ACCOUNT)
        .value("CMD_TYPE_MAX",pubsub::CMD_TYPE_MAX)
        .export_values()
        ;

    enum_<OffsetFlag>("OffsetFlag")
        .value("OffsetFlag_MIN",OffsetFlag_MIN)
        .value("OffsetFlag_OPEN",OffsetFlag_OPEN)
        .value("OffsetFlag_CLOSE",OffsetFlag_CLOSE)
        .value("OffsetFlag_CANCEL",OffsetFlag_CANCEL)
        .value("OffsetFlag_MAX",OffsetFlag_MAX)
        .export_values()
        ;

    enum_<Direction>("Direction")
        .value("Direction_MIN",Direction_MIN)
        .value("Direction_LONG",Direction_LONG)
        .value("Direction_SHORT",Direction_SHORT)
        .value("Direction_NET",Direction_NET)
        .value("Direction_MAX",Direction_MAX)
        .export_values()
        ;

    enum_<md::MarketType>("MarketType")
        .value("MarketType_MIN",md::MarketType_MIN)
        .value("TRADES",md::TRADES)
        .value("FUNDING_RATE",md::FUNDING_RATE)
        .value("DEPTH1",md::DEPTH1)
        .value("DEPTH5",md::DEPTH5)
        .value("DEPTH10",md::DEPTH10)
        .value("DEPTH20",md::DEPTH20)
        .value("KLINE_1m",md::KLINE_1m)
        .value("KLINE_1h",md::KLINE_1h)
        .value("KLINE_2h",md::KLINE_2h)
        .value("KLINE_4h",md::KLINE_4h)
        .value("KLINE_8h",md::KLINE_8h)
        .value("MBPType",md::MBPType)
        .value("MarketType_MAX",md::MarketType_MAX)
        .export_values()
    ;

    enum_<OrderType>("OrderType")
        .value("OrderType_MIN",OrderType_MIN)
        .value("OrderType_LIMIT",OrderType_LIMIT)
        .value("OrderType_MARKET",OrderType_MARKET)
        .value("OrderType_POST_ONLY",OrderType_POST_ONLY)
        .value("OrderType_FOK",OrderType_FOK)
        .value("OrderType_IOC",OrderType_IOC)
        .value("OrderType_UNKNOWN",OrderType_UNKNOWN)
//        .value("OrderType_OPTIMAL_LIMIT_IOC",OrderType_OPTIMAL_LIMIT_IOC)
        .value("OrderType_MAX",OrderType_MAX)
        .export_values()
        ;

    enum_<OrderStatus>("OrderStatus")
        .value("OrderStatus_MIN",OrderStatus_MIN)
        .value("OrderStatus_PENDING_NEW",OrderStatus_PENDING_NEW)
        .value("OrderStatus_REST_NEW",OrderStatus_REST_NEW)
        .value("OrderStatus_NEW",OrderStatus_NEW)
        .value("OrderStatus_PARTFILLED",OrderStatus_PARTFILLED)
        .value("OrderStatus_FILLED",OrderStatus_FILLED)
        .value("OrderStatus_REJECTED",OrderStatus_REJECTED)
        .value("OrderStatus_CANCELLING",OrderStatus_CANCELLING)
        .value("OrderStatus_CANCELED",OrderStatus_CANCELED)
        .value("OrderStatus_UNKNOWN",OrderStatus_UNKNOWN)
        .value("OrderStatus_FAILED",OrderStatus_FAILED)
        .value("OrderStatus_MAX",OrderStatus_MAX)
        .export_values()
        ;

    enum_<pubsub::QueryOrderType>("QueryOrderType")
        .value("QOT_MIN",pubsub::QOT_MIN)
        .value("QOT_ONE_INST",pubsub::QOT_ONE_INST)
        .value("QOT_MULTI_INST",pubsub::QOT_MULTI_INST)
        .value("QOT_MAX",pubsub::QOT_MAX)
        .export_values()
        ;

    enum_<pubsub::CancelOrderType>("CancelOrderType")
        .value("COT_MIN",pubsub::COT_MIN)
        .value("COT_ONE_INST",pubsub::COT_ONE_INST)
        .value("COT_MULTI_INST",pubsub::COT_MULTI_INST)
        .value("COT_MAX",pubsub::COT_MAX)
        .export_values()
        ;

    enum_<ApiSource>("ApiSource")
        .value("ApiSource_MIN",ApiSource_MIN)
        .value("ApiSource_ADD_NEW_ORDER",ApiSource_ADD_NEW_ORDER)
        .value("ApiSource_CANCEL_ORDER",ApiSource_CANCEL_ORDER)
        .value("ApiSource_QUERY_ORDER",ApiSource_QUERY_ORDER)
        .value("ApiSource_REST",ApiSource_REST)
        .value("ApiSource_WEBSOCKET",ApiSource_WEBSOCKET)
        .value("ApiSource_MAX",ApiSource_MAX)
        .export_values()
        ;

}

